# El nombre de la aplicación Spring
spring.application.name=api_test

#Puerto a utilizar
server.port=8585

# La URI del emisor para los tokens JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/spring-boot-realm-dev

# La URI para recuperar el JSON Web Key Set (JWKS) para validar los tokens JWT
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/spring-boot-realm-dev/protocol/openid-connect/certs

# El ID del cliente
jwt.auth.converter.resource-id=spring-client-api-rest

# El atributo en el token JWT que se usará como el principal
jwt.auth.converter.principal-attribute=email

# El nivel de registro para la biblioteca Keycloak
loggin.level.org.keycloak=DEBUG

#logging.level.root=DEBUG